// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tokndrkhxgmckuffbtrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRva25kcmtoeGdtY2t1ZmZidHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4ODExMjgsImV4cCI6MjA5MzQ1NzEyOH0.vDwV-1pLF2uGQ2o9h2glupQQP79Rxl6FqtkuwDpzT0A";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);