// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qgsqzirplodrvluwrnkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnc3F6aXJwbG9kcnZsdXdybmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxOTIxNzcsImV4cCI6MjA5MDc2ODE3N30.Q7oUosxrENqICyPvwcdE54IY6chAYi6jFgGkZV8a_Cg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);